// Generates supabase/videos_seed.sql from src/data/videoLibrary.ts.
// One-time migration: loads the bundled 129 clips into the `videos` table.
// Idempotent — re-running the SQL upserts on slug, so it's safe to apply twice.
//
// Usage: node scripts/gen_videos_seed.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, basename } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const src = readFileSync(join(root, "src/data/videoLibrary.ts"), "utf8");

// The file is `export const videoLibrary: VideoClip[] = [ ...JSON... ];`
// Slice out the array literal and parse it as JSON (entries are pure JSON objects).
const start = src.indexOf("[", src.indexOf("=")); // first "[" after the "=" (skip the VideoClip[] annotation)
const end = src.lastIndexOf("]");
if (start === -1 || end === -1) throw new Error("Could not find the videoLibrary array");
const clips = JSON.parse(src.slice(start, end + 1));

const sqlStr = (v) => "'" + String(v).replace(/'/g, "''") + "'";

const perCategory = new Map();
const rows = clips.map((c) => {
  const storagePath = basename(new URL(c.videoUrl).pathname); // e.g. "a-skip.mp4"
  const slug = storagePath.replace(/\.[^.]+$/, "");           // e.g. "a-skip"
  const n = perCategory.get(c.category) ?? 0;
  perCategory.set(c.category, n + 1);
  return `(${sqlStr(slug)}, ${sqlStr(c.name)}, ${sqlStr(c.category)}, ${sqlStr(storagePath)}, ${n})`;
});

const out = `-- AUTO-GENERATED by scripts/gen_videos_seed.mjs — do not edit by hand.
-- One-time migration of the bundled video library into the \`videos\` table.
-- Run AFTER supabase/videos.sql. Idempotent (upsert on slug).

insert into videos (slug, name, category, storage_path, sort_order) values
${rows.join(",\n")}
on conflict (slug) do update set
  name         = excluded.name,
  category     = excluded.category,
  storage_path = excluded.storage_path,
  sort_order   = excluded.sort_order;
`;

writeFileSync(join(root, "supabase/videos_seed.sql"), out);
console.log(`Wrote supabase/videos_seed.sql — ${rows.length} clips across ${perCategory.size} categories.`);
