// Generates src/data/videoLibrary.ts from the video batch manifests.
// Re-run after the media batch finishes to include every uploaded clip.
import { writeFileSync, existsSync, readFileSync, readdirSync } from "node:fs";

const SCRATCH = "/private/tmp/claude-501/-Users-bradykirtland-Desktop-Curtis-APP/bc4c2f26-fbcd-4897-81e0-76a902cebf40/scratchpad";
const SB = "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/";

const load = p => (existsSync(p) ? JSON.parse(readFileSync(p, "utf8")) : []);
// Sprint Drills: already uploaded — read them from the existing pilot data module
const sprintTs = "/Users/bradykirtland/Desktop/Curtis APP/src/data/sprintPilot.ts";
const sprint = [];
if (existsSync(sprintTs)) {
  const txt = readFileSync(sprintTs, "utf8");
  const re = /"name":\s*"([^"]+)"[\s\S]*?"videoUrl":\s*"([^"]+)"/g;
  let m;
  while ((m = re.exec(txt))) sprint.push({ prettyName: m[1], videoUrl: m[2] });
}
const batch = load(`${SCRATCH}/all_vids/manifest.json`);

function pretty(base) {
  return String(base).split("-").map(w => w ? w[0].toUpperCase() + w.slice(1) : w).join(" ");
}
function normCat(c) {
  if (!c) return "Other";
  if (/linked|misc/i.test(c)) return "Other";
  return c;
}

const clips = [];
const seen = new Set();
for (const m of sprint) {
  if (seen.has(m.videoUrl)) continue; seen.add(m.videoUrl);
  clips.push({ name: m.prettyName, category: "Sprint Drills", videoUrl: m.videoUrl });
}
for (const m of batch) {
  const url = SB + m.mp4Name;
  if (seen.has(url)) continue; seen.add(url);
  clips.push({ name: pretty(m.base), category: normCat(m.category), videoUrl: url });
}

// stable category ordering
const ORDER = ["Sprint Drills", "Multiple Jump", "Multiple Throw", "Ancillary Strength", "Ancillary Bike", "Mobility", "Other"];
clips.sort((a, b) => {
  const d = (ORDER.indexOf(a.category) + 1 || 99) - (ORDER.indexOf(b.category) + 1 || 99);
  return d !== 0 ? d : a.name.localeCompare(b.name);
});

const out =
`// AUTO-GENERATED by scripts/gen_video_library.mjs — do not edit by hand.
export interface VideoClip { name: string; category: string; videoUrl: string; }
export const videoLibrary: VideoClip[] = ${JSON.stringify(clips, null, 2)};
`;
writeFileSync("/Users/bradykirtland/Desktop/Curtis APP/src/data/videoLibrary.ts", out);

const byCat = {};
for (const c of clips) byCat[c.category] = (byCat[c.category] || 0) + 1;
console.log(`wrote videoLibrary.ts with ${clips.length} clips:`, byCat);
