// AUTO-GENERATED by scripts/gen_video_library.mjs — do not edit by hand.
export interface VideoClip { name: string; category: string; videoUrl: string; }
export const videoLibrary: VideoClip[] = [
  {
    "name": "A Skip",
    "category": "Sprint Drills",
    "videoUrl": "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/a-skip.mp4"
  },
  {
    "name": "A Switch",
    "category": "Sprint Drills",
    "videoUrl": "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/a-switch.mp4"
  },
  {
    "name": "A Switch Low",
    "category": "Sprint Drills",
    "videoUrl": "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/a-switch-low.mp4"
  },
  {
    "name": "B Skip",
    "category": "Sprint Drills",
    "videoUrl": "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/b-skip.mp4"
  },
  {
    "name": "B Switch",
    "category": "Sprint Drills",
    "videoUrl": "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/b-switch.mp4"
  },
  {
    "name": "C Skip",
    "category": "Sprint Drills",
    "videoUrl": "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/c-skip.mp4"
  },
  {
    "name": "Dribble Alt Fast Leg A Over The Ankle",
    "category": "Sprint Drills",
    "videoUrl": "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/dribble-alt-fast-leg-a-over-the-ankle.mp4"
  },
  {
    "name": "Dribble Alt Fast Leg B",
    "category": "Sprint Drills",
    "videoUrl": "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/dribble-alt-fast-leg-b.mp4"
  },
  {
    "name": "Dribble Ankle",
    "category": "Sprint Drills",
    "videoUrl": "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/dribble-ankle.mp4"
  },
  {
    "name": "Dribble Bleed Fast",
    "category": "Sprint Drills",
    "videoUrl": "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/dribble-bleed-fast.mp4"
  },
  {
    "name": "Dribble Bleed Slow",
    "category": "Sprint Drills",
    "videoUrl": "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/dribble-bleed-slow.mp4"
  },
  {
    "name": "Dribble Bounce Over The Ankle",
    "category": "Sprint Drills",
    "videoUrl": "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/dribble-bounce-over-the-ankle.mp4"
  },
  {
    "name": "Dribble Bounce Over The Knee",
    "category": "Sprint Drills",
    "videoUrl": "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/dribble-bounce-over-the-knee.mp4"
  },
  {
    "name": "Dribble Bounce Over The Shin",
    "category": "Sprint Drills",
    "videoUrl": "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/dribble-bounce-over-the-shin.mp4"
  },
  {
    "name": "Dribble Fast Leg A",
    "category": "Sprint Drills",
    "videoUrl": "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/dribble-fast-leg-a.mp4"
  },
  {
    "name": "Dribble Fast Leg B",
    "category": "Sprint Drills",
    "videoUrl": "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/dribble-fast-leg-b.mp4"
  },
  {
    "name": "Dribble Knee",
    "category": "Sprint Drills",
    "videoUrl": "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/dribble-knee.mp4"
  },
  {
    "name": "Dribble Pause",
    "category": "Sprint Drills",
    "videoUrl": "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/dribble-pause.mp4"
  },
  {
    "name": "Dribble Pause Hands On Hips",
    "category": "Sprint Drills",
    "videoUrl": "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/dribble-pause-hands-on-hips.mp4"
  },
  {
    "name": "Dribble Shin",
    "category": "Sprint Drills",
    "videoUrl": "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/dribble-shin.mp4"
  },
  {
    "name": "Dribble Skip",
    "category": "Sprint Drills",
    "videoUrl": "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/dribble-skip.mp4"
  },
  {
    "name": "Dribble Walk",
    "category": "Sprint Drills",
    "videoUrl": "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/dribble-walk.mp4"
  },
  {
    "name": "Dribble Walk Hands On Hips",
    "category": "Sprint Drills",
    "videoUrl": "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/dribble-walk-hands-on-hips.mp4"
  },
  {
    "name": "Scissor",
    "category": "Sprint Drills",
    "videoUrl": "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/scissor.mp4"
  },
  {
    "name": "Scissor Alt Fast Leg",
    "category": "Sprint Drills",
    "videoUrl": "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/scissor-alt-fast-leg.mp4"
  },
  {
    "name": "Scissor Low",
    "category": "Sprint Drills",
    "videoUrl": "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/scissor-low.mp4"
  },
  {
    "name": "Scissor Low Fast Leg",
    "category": "Sprint Drills",
    "videoUrl": "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/scissor-low-fast-leg.mp4"
  },
  {
    "name": "Single Leg A Skip",
    "category": "Sprint Drills",
    "videoUrl": "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/single-leg-a-skip.mp4"
  },
  {
    "name": "Single Leg B Skip",
    "category": "Sprint Drills",
    "videoUrl": "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/single-leg-b-skip.mp4"
  },
  {
    "name": "Bubkas",
    "category": "Ancillary Strength",
    "videoUrl": "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/bubkas.mp4"
  },
  {
    "name": "Bubkas 2",
    "category": "Ancillary Strength",
    "videoUrl": "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/bubkas-2.mp4"
  },
  {
    "name": "Clam Shells Maddy",
    "category": "Ancillary Strength",
    "videoUrl": "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/clam-shells-maddy.mp4"
  },
  {
    "name": "Db Alt Toe Touch",
    "category": "Ancillary Strength",
    "videoUrl": "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/db-alt-toe-touch.mp4"
  },
  {
    "name": "Db Curl",
    "category": "Ancillary Strength",
    "videoUrl": "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/db-curl.mp4"
  },
  {
    "name": "Db Curl Attmpt",
    "category": "Ancillary Strength",
    "videoUrl": "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/db-curl-attmpt.mp4"
  },
  {
    "name": "Hanging Eagles L Ups Knee Tucks",
    "category": "Ancillary Strength",
    "videoUrl": "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/hanging-eagles-l-ups-knee-tucks.mp4"
  },
  {
    "name": "L Ups",
    "category": "Ancillary Strength",
    "videoUrl": "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/l-ups.mp4"
  },
  {
    "name": "L Ups 2",
    "category": "Ancillary Strength",
    "videoUrl": "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/l-ups-2.mp4"
  },
  {
    "name": "Lunge Russian Twists",
    "category": "Ancillary Strength",
    "videoUrl": "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/lunge-russian-twists.mp4"
  },
  {
    "name": "Maddy",
    "category": "Ancillary Strength",
    "videoUrl": "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/maddy.mp4"
  },
  {
    "name": "Mike Jacky",
    "category": "Ancillary Strength",
    "videoUrl": "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/mike-jacky.mp4"
  },
  {
    "name": "Pull Ups",
    "category": "Ancillary Strength",
    "videoUrl": "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/pull-ups.mp4"
  },
  {
    "name": "Russian Twists Oh",
    "category": "Ancillary Strength",
    "videoUrl": "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/russian-twists-oh.mp4"
  },
  {
    "name": "Bike",
    "category": "Ancillary Bike",
    "videoUrl": "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/bike.mp4"
  },
  {
    "name": "Bike Maddy",
    "category": "Ancillary Bike",
    "videoUrl": "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/bike-maddy.mp4"
  },
  {
    "name": "Img 3195",
    "category": "Ancillary Bike",
    "videoUrl": "https://ujcysyepogzmglnxrvln.supabase.co/storage/v1/object/public/exercise-video/img-3195.mp4"
  }
];
